version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: stroy_control_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - stroy_pgdata:/var/lib/postgresql/data

volumes:
  stroy_pgdata:
